"""Add offline sync fields and receipt queue

Revision ID: 0d84d4b5507e
Revises: 8c9506fb76fb
Create Date: 2026-07-15 16:27:31.092936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d84d4b5507e'
down_revision = '8c9506fb76fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'whatsapp', name='receipt_channel'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='receipt_queue_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('synced', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_products_last_modified'), ['last_modified'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_synced'), ['synced'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_queue', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('synced', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('sync_attempts', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_receipt_queue'), ['receipt_queue'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_synced'), ['synced'], unique=False)
        batch_op.create_foreign_key('fk_sales_receipt_queue_id', 'receipt_queue', ['receipt_queue'], ['id'])

    with op.batch_alter_table('stockmovement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stockmovement', schema=None) as batch_op:
        batch_op.drop_column('synced')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_receipt_queue_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_synced'))
        batch_op.drop_index(batch_op.f('ix_sales_receipt_queue'))
        batch_op.drop_column('sync_attempts')
        batch_op.drop_column('synced')
        batch_op.drop_column('receipt_queue')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_synced'))
        batch_op.drop_index(batch_op.f('ix_products_last_modified'))
        batch_op.drop_column('synced')
        batch_op.drop_column('last_modified')

    op.drop_table('receipt_queue')
    # ### end Alembic commands ###
