"""made changes in column phone_number in MpesaTransaction

Revision ID: 8c9506fb76fb
Revises: e2b48f1a3456
Create Date: 2026-07-09 10:57:41.324728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c9506fb76fb'
down_revision = 'e2b48f1a3456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_transaction', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=400),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_transaction', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
