"""Add offline sync fields and receipt queue

Revision ID: ca358ab147bc
Revises: 0d84d4b5507e
Create Date: 2026-07-15 16:30:46.426032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca358ab147bc'
down_revision = '0d84d4b5507e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_receipt_queue'))
        batch_op.drop_column('receipt_queue')

    with op.batch_alter_table('stockmovement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stockmovement', schema=None) as batch_op:
        batch_op.drop_column('synced')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_queue', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_sales_receipt_queue'), ['receipt_queue'], unique=False)

    # ### end Alembic commands ###
